blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('',views.blog_page,name = 'blog_page'),
    path('blog/<int:blog_id>/',views.blog_detail,name = 'blog_detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from portfolio import urls

urlpatterns = [
    path('blog/', include('blog.urls', namespace='blog')),
    path('',include('portfolio.urls',namespace='portfolio')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views

app_name = 'potfolio'

urlpatterns = [
    path('',views.homepage,name = 'Homepage'),
    
         ]

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=150)
    image = models.ImageField(upload_to='portfolio/project/images')
    url = models.URLField(blank = True)
    
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Blog
# Create your views here.
def blog_page(request):
    blogs = Blog.objects.order_by('-created')[:4]
    context = {
        'blogs':blogs
    }
    return render(request,'blog/blog_page.html',context)

def blog_detail(request,blog_id):
    blog = get_object_or_404(Blog,pk = blog_id)
    context = {
        'blog':blog
    }
    return render(request,'blog/blog_detail.html',context)

portfolio/views.py
from django.shortcuts import render
from portfolio.models import Project

def homepage(request):
    projects = Project.objects.all()
    context = {
        'projects':projects
    }
    return render (request,'portfolio/homepage.html',context)

blog/templates/blog/blog_detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
   <div class="jumbotron container m-20">
        <strong class="display-1 lead">{{blog.title}}</strong>
        <br>
        <p class="lead">{{blog.body|safe}}</p>
        <br>
   </div>
{% endblock content %}
    

blog/templates/blog/blog_page.html
{% extends 'portfolio/base.html' %}

{% block title %}
    Blog
{% endblock title %}
    
{% block content %}
    <div class="jumbotron container mt-20">
        <h1>This is my personal blog page.</h1>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-body">
                {% for blog in blogs %}
                <h4 class="card-header">{{blog.created|date:'Y-m-d'}}</h4>
                <h1 class="card-title">{{blog.title}}</h4>
                    <p class="card-text">{{blog.body|striptags|truncatewords:10}}</p>
                    <button class="btn btn-outline-info"><a href="{% url 'blog:blog_detail' blog.id %}">See Detail</a></button>
                    {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}
    

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <link rel="icon" href="http://www.domain.com/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="http://127.0.0.1:8000/favicon.ico" type="image/x-icon" />
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>
    {% block title %}
        
    {% endblock title %}
        </title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'portfolio:Homepage' %}">Kushal</a>
            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse"
                data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    
                </ul>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blog:blog_page' %}">My Blogs<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">My Resume</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Facebook</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Twitter</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    {% block content %}
        
    {% endblock content %}
        

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
</body>

</html>

portfolio/templates/portfolio/homepage.html
{% extends 'portfolio/base.html' %}

{% block title %}
    Kushal
{% endblock title %}
    
{% block content %}
    <br>
    <br>
    {% load static %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col text-center pt-5">
                    <p class="lead"><strong>Mr.Kushal Subedi</strong></p>
                </div>
            </div>
        </div>
    </section>
    <img src="{% static 'portfolio/images/myprofile.jpg' %}" class="img-fluid rounded mx-auto d-block" alt="Profile"height="300px" width="300px">
      <section>
          <div class="container">
              <div class="row">
                  <div class="col text-center py-5">
                      <p><Strong>A bit about me</Strong></p>
                      <p class="lead">I am Kushal Subedi. Currently studying engineering in Pulchowk Engineering Campus of Nepal.
                          I am a professional web developer and an AI enthusiast. You can review my ongoing projects and ask for 
                          doing some favors for you.
                      </p>
                  </div>
              </div>
          </div>
      </section>
      <hr class="border-2px container">
      <section>
          <div class="row">
              <div class="col text-center py-5">
                  <p class="lead display-4"> <strong>Projects</strong> </p>
              </div>
          </div>
      </section>

    <section> 
        <div class="container">
            <div class="card-deck row no-gutters">
                {% for project  in projects %}
                <div class="col-md-3 d-flex mt-1">
                    <div class="card ">
                        <img src="{{project.image.url}}" alt="images" height="200px" width="25%"
                            class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{project.title}}</h5>
                            <p class="card-text">{{project.description}}</p>
                            <a href="#" class="btn btn-primary">Go to</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}
    